; configuration for blink
#include <avr/io.h>
#include "../include/AVRSpecialRegs.inc"


#define LED_PIN1		1
#define LED_DIR1     _DDRB
#define LED_PORT1    _PORTB

#define LED_PIN2		2
#define LED_DIR2     _DDRB
#define LED_PORT2    _PORTB

#define LED_PIN3		3
#define LED_DIR3     _DDRB
#define LED_PORT3    _PORTB

#define LED_PIN4		4
#define LED_DIR4     _DDRB
#define LED_PORT4    _PORTB

#define LED_PIN5		5
#define LED_DIR5     _DDRB
#define LED_PORT5    _PORTB
